version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        versions:
          - ">= 1.18"
          - "< 1.17"
